import type { Metadata } from "next";
import Link from "next/link";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <nav>
          <Link href="/">홈</Link>
          <Link href="/about">소개</Link>
          <Link href="/article">게시판</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
